### ISSUE TITLE
Support kube-state-metrics in addition to metrics-server

### ISSUE THREAD

**Issue by yogeek** [vladimirvivien/ktop#14]
First : great plugin, thanks !

On a cluster with [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) stack deployed, the [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-metrics-server) component replaces `metrics-server` to implement the K8S Metrics API.
We deleted metrics-server from our clusters now that we know that it is redundant with kube-state-metrics and consequently, the ktop displays `metrics: not connected`

It would be great if the plugin could detect `kube-state-metrics` when `metrics-server` is missing

**Comment by yogeek** [comment]
Sorry, it is in fact working with kube-state-metrics ! 👍

**Comment by vladimirvivien** [comment]
@yogeek actually, ktop solely relies on `metrics-server` for true metrics.
However, it has a fallback, if `metrics-server` is not found, it uses resource requests values instead of real metrics.

Nevertheless, this is an interesting point, and I have been researching how to use the `/metrics` API endpoint instead of `metrics-server`.
