### ISSUE TITLE
Pods panel is empty: couldn't fetch from API

### ISSUE THREAD

**Issue by Dentrax** [vladimirvivien/ktop#19]
I just tried the latest (v0.3.0) version and noticed ktop couldn't fill the pods.

![Screen Shot 2022-06-14 at 17 09 08](https://user-images.githubusercontent.com/16493751/173597791-9a17d13e-cbce-4ba8-87d6-e7294735503a.png)

But there are 570 pods:
```bash
$ kubectl get pods -A | wc -l

570
```

Any thoughts on this?

**Comment by vladimirvivien** [comment]
@Dentrax , well, if you made it this far (UI started), that means the account you are using has access to get namespaces, nodes and pods. There may be couple of issues:
* Account not allowed to fetch metrics (in which case it's a bug, program should at least draw other info)
* Possibly some other access rights issue caused by object retrieved.

Make sure account, for given cluster context, has sufficient rights to get/list objects namespaces, nodes, pods (metrics if present).

Hopefully that helped.

**Comment by vladimirvivien** [comment]
@Dentrax if you have admin rights you should be able to see everything (pods, namespaces, nodes, etc).
Other access rights include pulling (list) objects such as pvs, replicasets, jobs, etc (everything in the summary panel). Again, if you are using cluster admin, you should be able to see everything with no issue.

One quick check (if you don't mind) spin up a kind (or minikube) cluster locally and let me know if you are seeing empty panels once connected. Thanks.

**Comment by 7onn** [comment]
Hey everyone o/
I am facing the same issue of missing listed pods. 
I tested with a brand new `kind` cluster and it worked fine.

But when accessing my cluster endpoint which is a Teleport proxy for checking Okta's authentication, the pods are actually never listed.

**Comment by vladimirvivien** [comment]
Hi @7onn 
Apologies for the delay.  Your scenario, accessing your API server endpoint behind a proxy, is something that is very specific and I have no immediate solutions or suggestions for.

Does kubectl work with your teleport proxy? If so, do you have to pass any additional params to kubectl in order to talk to the API server?

**Comment by 7onn** [comment]
I tested with a nearly empty cluster behind teleport proxy. The pods were listed. The issue here is probably about the amount of pods.

**Comment by vladimirvivien** [comment]
@7onn Thank you for looking into this and confirming this may be an issue with the number of pods. The tool was not tested against clusters that large. I will look in the code to see if there is a quick workaround.  

One question: do you have the metrics server installed in your large cluster ?  The current implementation will use the metrics server for additional lookup for each pod it finds. I am thinking this may also adds to the issue.

Thanks.

**Comment by vladimirvivien** [comment]
Unfortunately, pods summary, from metrics server, only includes metrics not pods states (or any other data). It is necessary to retrieve additional info from the informer. Thanks again.

**Comment by shayneoneill** [comment]
I should note I had a similar problem. Rebuilt the metrics server (It was basically a smoking ruin from my predecessors inexperience) and now it works great.

**Comment by vladimirvivien** [comment]
@shayneoneill Interesting addition to this issue. Thanks for sharing.
What do you mean by rebuilt the metrics server? Do you mean rebuilt it from source ?
